# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################


from PyQt5 import QtCore
from PyQt5 import QtGui
from PyQt5 import QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(529, 426)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 210, 173, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.videoDelaySettings = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.videoDelaySettings.setContentsMargins(0, 0, 0, 0)
        self.videoDelaySettings.setObjectName("videoDelaySettings")
        self.videoDelayMinLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.videoDelayMinLabel.setObjectName("videoDelayMinLabel")
        self.videoDelaySettings.addWidget(self.videoDelayMinLabel)
        self.videoDelayMinSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.videoDelayMinSpinBox.setSingleStep(0.1)
        self.videoDelayMinSpinBox.setProperty("value", 3.0)
        self.videoDelayMinSpinBox.setObjectName("videoDelayMinSpinBox")
        self.videoDelaySettings.addWidget(self.videoDelayMinSpinBox)
        self.videoDelayMaxLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.videoDelayMaxLabel.setObjectName("videoDelayMaxLabel")
        self.videoDelaySettings.addWidget(self.videoDelayMaxLabel)
        self.videoDelayMaxSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.videoDelayMaxSpinBox.setSingleStep(0.1)
        self.videoDelayMaxSpinBox.setProperty("value", 10.0)
        self.videoDelayMaxSpinBox.setObjectName("videoDelayMaxSpinBox")
        self.videoDelaySettings.addWidget(self.videoDelayMaxSpinBox)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(370, 210, 138, 128))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.fragmentsAndCount = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.fragmentsAndCount.setContentsMargins(0, 0, 0, 0)
        self.fragmentsAndCount.setObjectName("fragmentsAndCount")
        self.fragmentLabel = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.fragmentLabel.setObjectName("fragmentLabel")
        self.fragmentsAndCount.addWidget(self.fragmentLabel)
        self.fragmentInSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_7)
        self.fragmentInSpinBox.setMinimum(1)
        self.fragmentInSpinBox.setMaximum(10)
        self.fragmentInSpinBox.setObjectName("fragmentInSpinBox")
        self.fragmentsAndCount.addWidget(self.fragmentInSpinBox)
        self.videoCountLabel = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.videoCountLabel.setObjectName("videoCountLabel")
        self.fragmentsAndCount.addWidget(self.videoCountLabel)
        self.videoCountSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_7)
        self.videoCountSpinBox.setMinimum(1)
        self.videoCountSpinBox.setMaximum(1000)
        self.videoCountSpinBox.setObjectName("videoCountSpinBox")
        self.fragmentsAndCount.addWidget(self.videoCountSpinBox)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 210, 170, 128))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.heightAndWidth = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.heightAndWidth.setContentsMargins(0, 0, 0, 0)
        self.heightAndWidth.setObjectName("heightAndWidth")
        self.widthLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.widthLabel.setObjectName("widthLabel")
        self.heightAndWidth.addWidget(self.widthLabel)
        self.widthSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.widthSpinBox.setMaximum(10000)
        self.widthSpinBox.setSingleStep(10)
        self.widthSpinBox.setProperty("value", 1080)
        self.widthSpinBox.setObjectName("widthSpinBox")
        self.heightAndWidth.addWidget(self.widthSpinBox)
        self.heightLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.heightLabel.setObjectName("heightLabel")
        self.heightAndWidth.addWidget(self.heightLabel)
        self.heightSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.heightSpinBox.setMaximum(10000)
        self.heightSpinBox.setSingleStep(10)
        self.heightSpinBox.setProperty("value", 1920)
        self.heightSpinBox.setObjectName("heightSpinBox")
        self.heightAndWidth.addWidget(self.heightSpinBox)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 499, 189))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.assets = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.assets.setContentsMargins(0, 0, 0, 0)
        self.assets.setObjectName("assets")
        self.assetsSettings = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.assetsSettings.setObjectName("assetsSettings")
        self.assets.addWidget(self.assetsSettings)
        self.assetsButtons = QtWidgets.QVBoxLayout()
        self.assetsButtons.setObjectName("assetsButtons")
        self.videoPathButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.videoPathButton.setObjectName("videoPathButton")
        self.assetsButtons.addWidget(self.videoPathButton)
        self.audioPathButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.audioPathButton.setObjectName("audioPathButton")
        self.assetsButtons.addWidget(self.audioPathButton)
        self.textPathButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.textPathButton.setObjectName("textPathButton")
        self.assetsButtons.addWidget(self.textPathButton)
        self.fontsPathButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fontsPathButton.setObjectName("fontsPathButton")
        self.assetsButtons.addWidget(self.fontsPathButton)
        self.assets.addLayout(self.assetsButtons)
        self.videoGenerationButton = QtWidgets.QPushButton(self.centralwidget)
        self.videoGenerationButton.setGeometry(QtCore.QRect(20, 360, 488, 28))
        self.videoGenerationButton.setObjectName("videoGenerationButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Загрузчик видео"))
        self.videoDelayMinLabel.setText(_translate("MainWindow", "Длина фрагмента мин."))
        self.videoDelayMaxLabel.setText(_translate("MainWindow", "Длина фрагмента макс."))
        self.fragmentLabel.setText(_translate("MainWindow", "Количество фрагментов"))
        self.videoCountLabel.setText(_translate("MainWindow", "Количество видео"))
        self.widthLabel.setText(_translate("MainWindow", "Ширина"))
        self.heightLabel.setText(_translate("MainWindow", "Высота"))
        self.videoPathButton.setText(_translate("MainWindow", "Видео"))
        self.audioPathButton.setText(_translate("MainWindow", "Аудио"))
        self.textPathButton.setText(_translate("MainWindow", "Текст"))
        self.fontsPathButton.setText(_translate("MainWindow", "Шрифты"))
        self.videoGenerationButton.setText(_translate("MainWindow", "Сгенерировать видео"))
    # retranslateUi

